import { Serie } from './serie.js';

export const dataSeries = [
  new Serie(1, "Breaking Bad", "AMC",  5, "http://illuminatilab.com/blog/wp-content/uploads/2013/10/Breaking-Bad.jpg", "Breaking Bad is an American television series created by Vince Gilligan. The show originally aired on AMC for five seasons.", "https://en.wikipedia.org/wiki/Breaking_Bad"),  
  new Serie(2, "Orange Is the New Black", "Netflix",  6, "https://m.media-amazon.com/images/M/MV5BMjIxNTcxNjkxMV5BMl5BanBnXkFtZTgwOTQ2NjU3NTE@._V1_.jpg", "Orange Is the New Black (OITNB) is an American television series created by Jenji Kohan. The series was produced by Lionsgate Television and aired on Netflix.", "https://en.wikipedia.org/wiki/Orange_Is_the_New_Black"),
  new Serie(3, "Game of Thrones", "HBO",  7, "https://cdn.culturagenial.com/es/imagenes/game-of-thrones-serie-og.jpg", "Game of Thrones is a drama and fantasy television series created for HBO by David Benioff and D. B. Weiss. It is an adaptation of the fantasy novel series A Song of Ice and Fire by George R. R. Martin.", "https://en.wikipedia.org/wiki/Game_of_Thrones"),
  new Serie(4, "The Big Bang Theory", "CBS",  12, "https://m.media-amazon.com/images/S/pv-target-images/4b63ef0284ce2942556d96bd39cef16f93384e974dabe61ff5e6b0ae1d794194.jpg", "The Big Bang Theory is an American sitcom created and produced by Chuck Lorre and Bill Prady. It premiered on September 24, 2007, on CBS.", "https://en.wikipedia.org/wiki/The_Big_Bang_Theory"),
  new Serie(5, "Sherlock", "BBC",  4, "https://images.ecestaticos.com/pkuk88gCz1sOGzVRa00LZm68dQg=/0x0:824x463/1600x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F33a%2Ff1b%2F45e%2F33af1b45e7c6e19bcb00fb71cdd48748.jpg", "Sherlock is a British television series created by Steven Moffat and Mark Gatiss. The series premiered on July 25, 2010, on BBC One.", "https://en.wikipedia.org/wiki/Sherlock_(TV_series)"),
  new Serie(6, "A Very English Scandal", "BBC",  2, "https://m.media-amazon.com/images/S/pv-target-images/3456fa769440b2db9de1e33d3d39c605a54ae36406d7461f8b63e86ef859a93e.jpg", "A Very English Scandal is a British television miniseries based on the book of the same name by John Preston. It premiered on BBC One on May 20, 2018.", "https://en.wikipedia.org/wiki/A_Very_English_Scandal"),
];